### ISSUE TITLE
Static Binary?

### ISSUE THREAD

**Issue by CanadianJeff** [parasyte/n64rd#7]
i'm not really good with scons but could this be changed to output n64rd as a static binary and not dynamic linked to libs

**Comment by parasyte** [comment]
There aren't a whole lot of libraries dynamically linked. Basically just `libc`:

```
$ ldd n64rd
        linux-vdso.so.1 (0x00007fff8d7c7000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fc81ced3000)
        /lib64/ld-linux-x86-64.so.2 (0x00007fc81d0db000)
```

I know vDSO can be a serious pain in some cases. Is that what made you ask about a static bin? (I would like to understand what lead you down this path. Maybe this is an XY problem?)

----

Anyway, the solution is pretty straightforward, but it took a few attempts to find the right incantation.

```patch
diff --git a/SConstruct b/SConstruct
index 1e8fdb8..53a5806 100644
--- a/SConstruct
+++ b/SConstruct
@@ -14,6 +14,8 @@ if conf.CheckHeader('sys/io.h'):
 
 env = conf.Finish()
 
+env.Append(LINKFLAGS="-static")
+
 ## Build
 env.Program([
     "n64rd.c", "gspro.c", "except.c"
```

That's it! Now it builds a static binary:

```
$ ldd n64rd
        not a dynamic executable
```
